### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by Pakhi-v**

### CODE REVIEW

**Comment by Pakhi-v** [comment]
@MasterIfeanyi please check updated readme. Let me know changes.

**Comment by MasterIfeanyi** [comment]
Hi, Great work. Please, could you add the following to the README file.

## Installation

The dependencies required are all included in the `package.json` file. They will all be installed by running the `npm install` command.

## Set-up

To start the project run `npm start`.

**Comment by MasterIfeanyi** [comment]
Capture23

Could you teach me how to make this kind of buttons ?

**Comment by Pakhi-v** [comment]
yes sure

**Comment by MasterIfeanyi** [comment]
Hi, this project is a javascript project. I think you should use /```javascript   ```/ instead of `bash` when adding npm commands.

**Comment by Pakhi-v** [comment]
Okay

**Comment by MasterIfeanyi** [comment]
Well Done. @Pakhi-v

**Pull request merged**
