### PR TITLE
Implemented using React

### PR DESCRIPTION
**Pull request by gokhalevedant06**

### CODE REVIEW

**Comment by MasterIfeanyi** [comment]
Hi, sorry I did not mention this earlier, I would love it if you could use bootstrap 5. Also, add this [css](https://stagbin.tk/emim1y3) styling to the index.css file

**Comment by gokhalevedant06** [comment]
I have used Chakra UI for the styles. Do you want me to redo the styling part ?

**Comment by MasterIfeanyi** [comment]
Yes, I am sorry I did not mention this earlier. I would love it if you could use bootstrap 5. Also, add this [css](https://stagbin.tk/emim1y3) styling to the index.css file

**Comment by gokhalevedant06** [comment]
Okay. Will do it

**Comment by gokhalevedant06** [comment]
I have done the requried changes

**Comment by MasterIfeanyi** [comment]
Well done @gokhalevedant06 Great job.

**Pull request merged**
