### PR TITLE
added restart button to the question component

### PR DESCRIPTION
**Pull request by Nirbhayparmar**
I have added restart button in the question component to make it restart whenever we want.

here is the screenshot of button added-

restart

Please check it, here in changed file due to my prettier configuration, it makes all code formated so all code is shown as changed, but only code related to added button is only changed.

image

and

image

### CODE REVIEW

**Comment by MasterIfeanyi** [comment]
I thought you said you did not know React ?

**Comment by MasterIfeanyi** [comment]
Nice work by the way and thank you for adding images, it made review a lot easier.

**Comment by MasterIfeanyi** [comment]
@Nirbhayparmar Respond please.

**Comment by Nirbhayparmar** [comment]
> I thought you said you did not know React ?

I still don't know react but, this time by reverse engineering and analyzing the code I am able to implement the restart button.

**Comment by Nirbhayparmar** [comment]
> @Nirbhayparmar Respond please.

 Sorry for that, I am having some work, so not able to respond to you.

**Comment by Nirbhayparmar** [comment]
does this PR is okay or not?

**Comment by MasterIfeanyi** [comment]
> > I thought you said you did not know React ?
> 
> I still don't know react but, this time by reverse engineering and analyzing the code I am able to implement the restart button.

This guy said he "reverse engineered" are you Tony Stark (Iron-man) 😂🤣😂🤣😆😂😂

**Comment by Nirbhayparmar** [comment]
> > > I thought you said you did not know React ?
> > 
> > 
> > I still don't know react but, this time by reverse engineering and analyzing the code I am able to implement the restart button.
> 
> This guy said he "reverse engineered" are you Tony Stark (Iron-man) 😂🤣😂🤣😆😂😂

Kind of 😂🤣:-)

**Pull request merged**
