### PR TITLE
Add random questions and answers

### LINKED ISSUE #12: Randomize the questions and answers
Currently the questions and answers follows the same sequential order, after playing for a while it's possible to memorize the answers.

I would like to implement a randomization function that prevents that by generating random array positions each time the users begin playing. If you find this helpful please consider assigning me.

### PR DESCRIPTION
**Pull request by mateusabelli**
## List of changes

- Random question and answers functionality
- Fixed console warnings
- Code format with Prettier
- Styling bug fix

## Description

A randomizer functionality has been added, using the `useEffect` hook so when the page reloads a random array of options will be generated and random questions ids too, making the game experience much better.
[Algorithm credits](https://stackoverflow.com/a/46545530)

The console warnings saying `Warning: Each child in a list should have a unique "key" prop` have been fixed by adding key property where applicable and simplifying a `ternary` to an `if` statement.

There has been improvements made with the code formatting by using `Prettier`, now the code has better readability.

A small fix for the styles was also made so now the options won't appear too close to each other, this was solved by using a `gap` property.

**Fixes #12**

## Type of change

- [x] Small Bug fix
- [x] New feature

### CODE REVIEW

**Comment by MasterIfeanyi** [comment]
GitHub says "5 checks have failed". Do you know why ?

**Comment by mateusabelli** [comment]
Hello @MasterIfeanyi, yeah I've just read the logs from netlify. Looks like there were a few errors left in the code that I didn't noticed while running the dev server, it's okay I'm marking the PR as Draft and I'm going to take a closer look tomorrow

**Comment by mateusabelli** [comment]
### Bug fix for the commit https://github.com/MasterIfeanyi/My-own-quiz-game/pull/13/commits/8ffdd514ec77b1087a3b13cedbc5ca5a90f766d4

**https://github.com/MasterIfeanyi/My-own-quiz-game/pull/13/commits/819c593a8eb95598e328131d7dca31d2c36521ec List of changes** 

- Added comments
- Questions are now declared inside useEffect to fix the [react-hooks/exhaustive-deps](https://blog.logrocket.com/understanding-react-exhaustive-deps-linting-warning/) warning. The questions array were being referenced outside the useEffect making then an outside dependency, the easiest solution was to move the declaration inside the function.
- Revert the if statement to a ternary to fix the [array-callback-return](https://eslint.org/docs/latest/rules/array-callback-return) warning. The if statement was causing the map to not have a defined return, now it directly returns the ternary with the components, else null to also prevent the [react key prop](https://reactjs.org/docs/lists-and-keys.html) warning

**Comment by mateusabelli** [comment]
@MasterIfeanyi The merge conflict has been solved, I've tested the app on my machine and on the preview deployment, everything seems fine now. Let know if you have any questions

**Pull request closed without merging**
